name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need a full checkout for `git describe`

      - name: Install Go 1.x
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: go build -v -o main.exe main.go
      - name: Build
        if: matrix.os == 'windows-latest'
        run: ./main.exe
